# *****************************************************************************
#
# NOTE: Unlike the standard Figaro implementation this configuration file is
# checked into the repository.
#
# As such only include "dummy values" or those values necessary for booting in
# development mode.
#
# *****************************************************************************
#
# The purpose of the config/application.yml is to define additional ENV
# variables that are injected into the Rails application.
#
# The applicatino's ENV variables first come from the ENV of the shell profile,
# then any missing ENV variables are injected via the config/application.yml
# file.
#
# See https://github.com/laserlemon/figaro for further details on usage
#
# Add configuration values here, as shown below. Also add those keys to
# config/initializers/figaro_required_env_variables.rb
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
