# *****************************************************************************
#
# NOTE: Unlike the standard Figaro implementation this configuration file is
# checked into the repository.
#
# As such only include "dummy values" or those values necessary for booting in
# development mode.
#
# *****************************************************************************
#
# The purpose of the config/application.yml is to define additional ENV
# variables that are injected into the Rails application.
#
# The applicatino's ENV variables first come from the ENV of the shell profile,
# then any missing ENV variables are injected via the config/application.yml
# file.
#
# See https://github.com/laserlemon/figaro for further details on usage
#
# Add configuration values here, as shown below. Also add those keys to
# config/initializers/figaro_required_env_variables.rb
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  application_database_name: curax_development
  blacklight_adapter: solr
  cable_adapter: async
  devise_secret_key: b7adb179eac5f12b64c17a94f53a5819488ad2e190bbac281880501e0a5e3076548ad9a7e689680f333864242ee893eb986f870b432601ca3f52da6e6e435f54
  fedora_base_path: /dev
  fedora_password: fedoraAdmin
  fedora_url: http://127.0.0.1:8984/rest
  fedora_username: fedoraAdmin
  redis_host: localhost
  redis_port: '6379'
  secret_key_base: 30fe58c029e2f851db78db03cc60677ae46d582695b0db61a6e9d20a690aed94f4aad6428e756bcfe5ab85182e5474cef31140916587238c580456973e9c8684
  solr_url: http://127.0.0.1:8983/solr/hydra-development

test:
  application_database_name: curax_test
  blacklight_adapter: solr
  cable_adapter: async
  devise_secret_key: b7adb179eac5f12b64c17a94f53a5819488ad2e190bbac281880501e0a5e3076548ad9a7e689680f333864242ee893eb986f870b432601ca3f52da6e6e435f54
  fedora_base_path: /dev
  fedora_password: fedoraAdmin
  fedora_url: http://127.0.0.1:8986/rest
  fedora_username: fedoraAdmin
  redis_host: localhost
  redis_port: '6379'
  secret_key_base: 30fe58c029e2f851db78db03cc60677ae46d582695b0db61a6e9d20a690aed94f4aad6428e756bcfe5ab85182e5474cef31140916587238c580456973e9c8684
  solr_url: http://127.0.0.1:8985/solr/hydra-test
