development:
  adapter: <%= Figaro.env.blacklight_adapter %>
  url: <%= Figaro.env.solr_url %>
test:
  adapter: <%= Figaro.env.blacklight_adapter %>
  url: <%= Figaro.env.solr_url %>
staging:
  adapter: <%= Figaro.env.blacklight_adapter %>
  url: <%= Figaro.env.solr_url %>
