development:
  adapter: <%= Figaro.env.cable_adapter %>

test:
  adapter: <%= Figaro.env.cable_adapter %>

# production:
#   adapter: <%= Figaro.env.cable_adapter %>
#   url: <%= Figaro.env.cable_adapter_url %>
#   channel_prefix: <%= Figaro.env.cable_adapter_channel_prefix %>
