# Welcome Rails developer. If you are looking to add secrets, please review the README.
# We prefer instead to use Figaro (as configured in confg/application.yml)

development:
  secret_key_base: <%= Figaro.env.secret_key_base %>

test:
  secret_key_base: <%= Figaro.env.secret_key_base %>

staging:
  secret_key_base: <%= Figaro.env.secret_key_base %>
